vagrantfile:
    vm:
        hostname: Project
        synced_folder:
            vflsf_z64gtcw0od4i:
                target: /var/www/project
apache:
    vhosts:
        av_nvjebw8jor9g:
            servername: project.dev
            serveraliases:
                - project.dev
                - '*.vagrantshare.com'
            docroot: /var/www/project/web
            directories:
                avd_5xa3ga631b0o:
                    path: /var/www/project
                    custom_fragment: "## XSEND"
mysql:
    settings:
        root_password: uraan123
    databases:
        mysqlnd_dcghdzjctstf:
            name: project_db
            sql: ''

