vagrantfile:
    vm:
        hostname: Conrad
        synced_folder:
            vflsf_z64gtcw0od4i:
                target: /var/www/conrad
apache:
    vhosts:
        av_nvjebw8jor9g:
            servername: conrad.dev
            serveraliases:
                - conrad.dev
                - '*.vagrantshare.com'
            docroot: /var/www/conrad/web
            directories:
                avd_5xa3ga631b0o:
                    path: /var/www/conrad
                    custom_fragment: "## XSEND"
mysql:
    settings:
        root_password: uraan123
    databases:
        mysqlnd_dcghdzjctstf:
            name: conrad_db
            sql: ''

